/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package componentepractica1;
import java.awt.Color;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.help.HelpBroker;
import javax.help.HelpSet;

/**
 *
 * @author Dams2
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        ayuda();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        componenteColor2 = new componentepractica1.ComponenteColor();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        componenteColor3 = new componentepractica1.ComponenteColor();
        jLabel3 = new javax.swing.JLabel();
        componenteColor4 = new componentepractica1.ComponenteColor();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        componenteColor2.setPigmento(new Pigmento(new Color(255,0,0),new Color(255,255,0)));
        componenteColor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                componenteColor2ActionPerformed(evt);
            }
        });
        componenteColor2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                componenteColor2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                componenteColor2FocusLost(evt);
            }
        });

        jLabel1.setText("Nombre");

        jLabel2.setText("Apellidos");

        componenteColor3.setPigmento(new Pigmento(new Color(255,0,0),new Color(255,255,0)));
        componenteColor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                componenteColor3ActionPerformed(evt);
            }
        });
        componenteColor3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                componenteColor3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                componenteColor3FocusLost(evt);
            }
        });

        jLabel3.setText("Telefono");

        componenteColor4.setPigmento(new Pigmento(new Color(255,0,0),new Color(255,255,0)));
        componenteColor4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                componenteColor4ActionPerformed(evt);
            }
        });
        componenteColor4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                componenteColor4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                componenteColor4FocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(componenteColor2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel3))
                            .addComponent(jLabel2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(componenteColor3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(componenteColor4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(166, 166, 166))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(componenteColor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(componenteColor3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(componenteColor4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void componenteColor2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_componenteColor2MouseClicked
       
    }//GEN-LAST:event_componenteColor2MouseClicked

    private void componenteColor2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_componenteColor2FocusGained
        componenteColor2.setBackground(componenteColor2.getTono().getColorFondo());
         componenteColor2.setForeground(componenteColor2.getTono().getColorTexto());
    }//GEN-LAST:event_componenteColor2FocusGained

    private void componenteColor2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_componenteColor2FocusLost
         componenteColor2.setBackground(Color.WHITE);
         componenteColor2.setForeground(Color.BLACK);
    }//GEN-LAST:event_componenteColor2FocusLost

    private void componenteColor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_componenteColor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_componenteColor2ActionPerformed

    private void componenteColor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_componenteColor3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_componenteColor3ActionPerformed

    private void componenteColor3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_componenteColor3FocusGained
         componenteColor3.setBackground(componenteColor2.getTono().getColorFondo());
         componenteColor3.setForeground(componenteColor2.getTono().getColorTexto());
    }//GEN-LAST:event_componenteColor3FocusGained

    private void componenteColor3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_componenteColor3FocusLost
        componenteColor3.setBackground(Color.WHITE);
         componenteColor3.setForeground(Color.BLACK);
    }//GEN-LAST:event_componenteColor3FocusLost

    private void componenteColor4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_componenteColor4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_componenteColor4ActionPerformed

    private void componenteColor4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_componenteColor4FocusGained
         componenteColor4.setBackground(componenteColor2.getTono().getColorFondo());
         componenteColor4.setForeground(componenteColor2.getTono().getColorTexto());
    }//GEN-LAST:event_componenteColor4FocusGained

    private void componenteColor4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_componenteColor4FocusLost
       componenteColor4.setBackground(Color.WHITE);
         componenteColor4.setForeground(Color.BLACK);
    }//GEN-LAST:event_componenteColor4FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    
     private void ayuda(){
        try 
        {
            // Carga el fichero de ayuda
            File fichero = new File("help"+File.separator+"help_set.hs");
            URL hsURL = fichero.toURI().toURL();

            // Crea el HelpSet y el HelpBroker
            HelpSet helpset = new HelpSet(getClass().getClassLoader(), hsURL);
            HelpBroker hb = helpset.createHelpBroker();

            // Pone ayuda a item de menu al pulsarlo y a F1 en ventana
          
            hb.enableHelpKey(getRootPane(),"aplicacion",helpset);
        } 
        catch (Exception e) 
        {
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private componentepractica1.ComponenteColor componenteColor2;
    private componentepractica1.ComponenteColor componenteColor3;
    private componentepractica1.ComponenteColor componenteColor4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
