/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package componentepractica1;
import java.awt.Color;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.help.HelpBroker;
import javax.help.HelpSet;

/**
 *
 * @author Dams2
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        ponAyuda();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        componenteColorDos = new componentepractica1.ComponenteColor();
        componenteColorTres = new componentepractica1.ComponenteColor();
        jPanel1 = new javax.swing.JPanel();
        componenteColorUno = new componentepractica1.ComponenteColor();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("1");

        componenteColorUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                componenteColorUnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(componenteColorUno, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(componenteColorUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(componenteColorDos, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(componenteColorTres, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(414, 414, 414))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(componenteColorDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(componenteColorTres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void componenteColor2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_componenteColor2MouseClicked
       
    }//GEN-LAST:event_componenteColor2MouseClicked

    private void componenteColor2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_componenteColor2FocusGained
        componenteColorUno.setBackground(componenteColorUno.getTono().getColorFondo());
         componenteColorUno.setForeground(componenteColorUno.getTono().getColorTexto());
    }//GEN-LAST:event_componenteColor2FocusGained

    private void componenteColor2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_componenteColor2FocusLost
         componenteColorUno.setBackground(Color.WHITE);
         componenteColorUno.setForeground(Color.BLACK);
    }//GEN-LAST:event_componenteColor2FocusLost

    private void componenteColor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_componenteColor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_componenteColor2ActionPerformed

    private void componenteColor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_componenteColor3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_componenteColor3ActionPerformed

    private void componenteColor3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_componenteColor3FocusGained
         componenteColorDos.setBackground(componenteColorUno.getTono().getColorFondo());
         componenteColorDos.setForeground(componenteColorUno.getTono().getColorTexto());
    }//GEN-LAST:event_componenteColor3FocusGained

    private void componenteColor3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_componenteColor3FocusLost
        componenteColorDos.setBackground(Color.WHITE);
         componenteColorDos.setForeground(Color.BLACK);
    }//GEN-LAST:event_componenteColor3FocusLost

    private void componenteColor4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_componenteColor4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_componenteColor4ActionPerformed

    private void componenteColor4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_componenteColor4FocusGained
         componenteColorTres.setBackground(componenteColorUno.getTono().getColorFondo());
         componenteColorTres.setForeground(componenteColorUno.getTono().getColorTexto());
    }//GEN-LAST:event_componenteColor4FocusGained

    private void componenteColor4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_componenteColor4FocusLost
       componenteColorTres.setBackground(Color.WHITE);
         componenteColorTres.setForeground(Color.BLACK);
    }//GEN-LAST:event_componenteColor4FocusLost

    private void componenteColorUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_componenteColorUnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_componenteColorUnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    
     private void ponAyuda(){
        try 
        {
            // Carga el fichero de ayuda
            File fichero = new File("help"+File.separator+"help_set.hs");
            URL hsURL = fichero.toURI().toURL();

            // Crea el HelpSet y el HelpBroker
            HelpSet helpset = new HelpSet(getClass().getClassLoader(), hsURL);
            HelpBroker hb = helpset.createHelpBroker();

            // Pone ayuda a item de menu al pulsarlo y a F1 en ventana
          
            hb.enableHelpKey(getRootPane(),"aplicacion",helpset);
        } 
        catch (Exception e) 
        {
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private componentepractica1.ComponenteColor componenteColorDos;
    private componentepractica1.ComponenteColor componenteColorTres;
    private componentepractica1.ComponenteColor componenteColorUno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
