/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package componentepractica1;

import java.awt.Color;

public class TonoPanel extends javax.swing.JPanel {

    public TonoPanel() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabelColorFondo = new javax.swing.JLabel();
        jLabelColorTexto = new javax.swing.JLabel();
        jTextFieldColorFondo = new javax.swing.JTextField();
        jTextFieldColorTexto = new javax.swing.JTextField();

        jLabelColorFondo.setText("Fondo");

        jLabelColorTexto.setText("Texto");

        jTextFieldColorFondo.setText("0,0,0");
        jTextFieldColorFondo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldColorFondoActionPerformed(evt);
            }
        });

        jTextFieldColorTexto.setText("255,255,255");
        jTextFieldColorTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldColorTextoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabelColorTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldColorTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelColorFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldColorFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelColorTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldColorTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldColorFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelColorFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldColorTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldColorTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldColorTextoActionPerformed

    private void jTextFieldColorFondoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldColorFondoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldColorFondoActionPerformed

    public Tono getValue()
    {
        String[] string1 = jTextFieldColorFondo.getText().toString().split(",");
        String[] string2 = jTextFieldColorTexto.getText().toString().split(",");
        
        Color colorFondo= new Color(Integer.parseInt(string1[0]),Integer.parseInt(string1[1]),Integer.parseInt(string1[2]));
        Color colorTexto= new Color(Integer.parseInt(string2[0]),Integer.parseInt(string2[1]),Integer.parseInt(string2[2]));
        
        return new Tono(colorFondo,colorTexto);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabelColorFondo;
    private javax.swing.JLabel jLabelColorTexto;
    private javax.swing.JTextField jTextFieldColorFondo;
    private javax.swing.JTextField jTextFieldColorTexto;
    // End of variables declaration//GEN-END:variables
}
